;zend_extension=xdebug
xdebug.mode=debug,develop,coverage
xdebug.start_with_request=yes
xdebug.discover_client_host=1
xdebug.trigger_value=XDEBUG_SESSION_START
xdebug.idekey=phpstorm
xdebug.client_port=9003
xdebug.client_host=host.docker.internal
xdebug.profiler_output_name=cachegrind-out.%p.cg

